stages:
  - build

build_debian_12:
  stage: build
  image: .ci/debian12
  tags:         
    - DESY-IT
  only:
    - branches
  script:
    - TANGO_DIR=/usr/share/pogo/preferences make
  # artifacts:     
  #   name: "$PROJECT_NAME"     

  #   paths:       
  #     - *.so*
