name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: '30 0 22 * *'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

defaults:
  run:
    shell: bash

jobs:
  dpkg:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [debian13, debian12, debian11]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Build the docker
        env:
          OS: ${{ matrix.os }}
        run: docker build -t build .ci/${OS}

      - name: Run the docker
        run: docker run --name build -i -d -v"$PWD:/home/p00user/src"  build

      - name: Build all
        run: docker  exec build /bin/bash -c "make"


      - name: Stop the docker
        run: docker container stop build

